## Numpy

- It is the fundamental package of scientific computing in python
- It also has funtion for working in domain of linear algerbra, fourier transformation and matices.

Array

- It story only contigous memory locations
- It hold fixed number of item and that sould be same datatype

Installing numpy in vs code

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.1 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
print("Hello")

Hello


Importing numpy

In [2]:
  import numpy as np

- Array:- It does not store comma spreated value

In [3]:
arr= np.array([10,20,30,40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


1. 1D array

In [7]:
arr=np.array([10,20,30])
print("This is 1D array",arr)

This is 1D array [10 20 30]


2. 2D array

In [14]:
arr=np.array([[10,20,30],[40,50,60]])
print("This is 2D array ",arr)

This is 2D array  [[10 20 30]
 [40 50 60]]


3. 3D array

In [15]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("This is 3D array ",arr)

This is 3D array  [[10 20 30]
 [40 50 60]
 [70 80 90]]


Slicing:- printing sepecific element of array

In [16]:
arr= np.array([10,20,30])
print (arr[:2])

[10 20]


In [32]:
# 2D array
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:2,0:2])
#print 70,80
print(arr[1,2:4])
#print 20,30
print(arr[0,1:3])

[[10 20]
 [50 60]]
[70 80]
[20 30]


In [34]:
# 3D array
arr=np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
#print 60,80 from third array 
print(arr[2,2:4])


[60 80]


In [ ]:
# Importing numpy library
import numpy as np

print(np.__version__)

2.0.0


In [ ]:
# Attributes

# Number of dimensions of the array
print("Number of dimensions (ndim):", array2.ndim) 

# Dimensions of the array
print("Shape of the array (shape):", array2.shape) 

# Number of elements in the array
print("Total number of elements (size):", array2.size)

# Data type of the array elements
print("Data type of elements (dtype):", array2.dtype) 

# Size of each element in bytes 
print("Size in bytes of each element (itemsize):", array2.itemsize)  

# Total bytes consumed by the elements
print("Total bytes consumed by elements (nbytes):", array2.nbytes)  

Number of dimensions (ndim): 2
Shape of the array (shape): (2, 3)
Total number of elements (size): 6
Data type of elements (dtype): int64
Size in bytes of each element (itemsize): 8
Total bytes consumed by elements (nbytes): 48


In [ ]:
# Functions

# Create an array of zeros
zeros_array = np.zeros((3, 3))  
print("Array of zeros:\n", zeros_array)

# Create an array of ones
ones_array = np.ones((2, 4))  
print("Array of ones:\n", ones_array)

# Create an array of random values
random_array = np.random.rand(3, 2)  
print("Random array:\n", random_array)

# Create an array with a range of values
range_array = np.arange(0, 10, 2) 
print("Range array:", range_array)

# Create an array of evenly spaced values
linspace_array = np.linspace(0, 1, 5) 
print("Linspace array:", linspace_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random array:
 [[0.83746899 0.04753412]
 [0.80560327 0.86576562]
 [0.7964766  0.51451454]]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Indexing and slicing

# Access a single element
element = array1[2]
print("Accessed element:", element)

# Slice a 1D array
slice_1d = array1[1:4]  
print("Sliced 1D array:", slice_1d)

# Slice a 2D array
slice_2d = array2[:, 1:3] 
print("Sliced 2D array:\n", slice_2d)


Accessed element: 3
Sliced 1D array: [2 3 4]
Sliced 2D array:
 [[2 3]
 [5 6]]


In [ ]:
# Broadcasting
broadcast_a = array1 + 10  # Broadcast addition
print("Broadcasted array:", broadcast_a)

# Broadcasting
broadcast_b = array1 - 10  # Broadcast subtraction
print("Broadcasted array:", broadcast_b)

Broadcasted array: [11 12 13 14 15]
Broadcasted array: [-9 -8 -7 -6 -5]


In [ ]:
# Operators

# Element-wise addition
sum_array = array1 + array1 
print("Element-wise addition:", sum_array)

# Element-wise multiplication
product_array = array1 * array1  
print("Element-wise multiplication:", product_array)

# Dot product
dot_product = np.dot(array1, array1)  
print("Dot product:", dot_product)

Element-wise addition: [ 2  4  6  8 10]
Element-wise multiplication: [ 1  4  9 16 25]
Dot product: 55


In [ ]:
# Array manipulation

# Reshape the array
reshaped_array = array1.reshape((5, 1))  
print("Reshaped array:\n", reshaped_array)

# Flatten the array
flattened_array = array2.flatten() 
print("Flattened array:", flattened_array)


Reshaped array:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Flattened array: [1 2 3 4 5 6]


In [ ]:
# Stacking arrays

# Vertical stack
vstack_array = np.vstack((array1, array1))
print("Vertically stacked array:\n", vstack_array)

# Horizontal stack
hstack_array = np.hstack((array1, array1))
print("Horizontally stacked array:", hstack_array)

Vertically stacked array:
 [[1 2 3 4 5]
 [1 2 3 4 5]]
Horizontally stacked array: [1 2 3 4 5 1 2 3 4 5]


In [ ]:
# Splitting arrays: split the array into parts

split_array = np.array_split(array1, 5)
print("Split array:", split_array)


Split array: [array([1]), array([2]), array([3]), array([4]), array([5])]


In [ ]:
# Adding and removing elements

# Add elements to the array
added_array = np.append(array1, [6, 7])
print("Array after addition:", added_array)

# Remove elements from the array
removed_array = np.delete(array1, [1, 2])
print("Array after removal:", removed_array)

# Insert elements into the array
inserted_array = np.insert(array1, 2, [8, 9])
print("Array after insertion:", inserted_array)

Array after addition: [1 2 3 4 5 6 7]
Array after removal: [1 4 5]
Array after insertion: [1 2 8 9 3 4 5]


In [ ]:
# Mathematical functions

# Square root of each element
sqrt_array = np.sqrt(array1) 
print("Square root of array1:", sqrt_array)

# Exponential of each element
exp_array = np.exp(array1)
print("Exponential of array1:", exp_array)

# Natural logarithm of each element
log_array = np.log(array1)
print("Logarithm of array1:", log_array)

Square root of array1: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential of array1: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm of array1: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
# Conditional Selection 
# Select elements that are even
conditional_selection = array2[array2 % 2 == 0]  
print("Even elements in array2:", conditional_selection)

Even elements in array2: [2 4 6]


In [ ]:
# Boolean indexing
boolean_index = array1[array1 > 3]  
print("Elements greater than 3:", boolean_index)

Elements greater than 3: [4 5]


In [ ]:
# Statistical operations

# Mean of the elements
mean_value = np.mean(array1) 
print("Mean of array1:", mean_value)

# Sum of the elements
sum_value = np.sum(array1)  
print("Sum of array1:", sum_value)

# Standard deviation of the elements
std_value = np.std(array1)  
print("Standard deviation of array1:", std_value)

# Variance of the elements
var_value = np.var(array1)
print("Variance of array1:", var_value)

# Minimum value in the array
min_value = np.min(array1)  
print("Minimum value in array1:", min_value)

# Maximum value in the array
max_value = np.max(array1)  
print("Maximum value in array1:", max_value)

# Index of the minimum value
argmin_value = np.argmin(array1)  
print("Index of minimum value in array1:", argmin_value)

# Index of the maximum value
argmax_value = np.argmax(array1)  
print("Index of maximum value in array1:", argmax_value)

Mean of array1: 3.0
Sum of array1: 15
Standard deviation of array1: 1.4142135623730951
Variance of array1: 2.0
Minimum value in array1: 1
Maximum value in array1: 5
Index of minimum value in array1: 0
Index of maximum value in array1: 4


In [ ]:
# Cumulative sum and product

# Cumulative sum of elements
cumsum_array = np.cumsum(array1)  
print("Cumulative sum of array1:", cumsum_array)

# Cumulative product of elements
cumprod_array = np.cumprod(array1) 
print("Cumulative product of array1:", cumprod_array)

Cumulative sum of array1: [ 1  3  6 10 15]
Cumulative product of array1: [  1   2   6  24 120]


In [ ]:
# Sorting arrays

# Sort the array
sorted_array = np.sort(array1)  
print("Sorted array1:", sorted_array)

# Indices of sorted elements
argsort_array = np.argsort(array1)
print("Indices of sorted array1:", argsort_array)

Sorted array1: [1 2 3 4 5]
Indices of sorted array1: [0 1 2 3 4]


In [ ]:
# Unique elements
unique_elements = np.unique(array1) 
print("Unique elements in array1:", unique_elements)

Unique elements in array1: [1 2 3 4 5]


In [ ]:
# Transpose and inverse of a matrix
transpose_matrix = array2.T  
print("Transpose of array2:\n", transpose_matrix)

# Inverse of a matrix (only for square matrices)
square_matrix = np.array([[1, 2], [3, 4]])
inverse_matrix = np.linalg.inv(square_matrix)  
print("Inverse of square_matrix:\n", inverse_matrix)

Transpose of array2:
 [[1 4]
 [2 5]
 [3 6]]
Inverse of square_matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# Linear algebra operations
# Matrix product
matrix_product = np.dot(array2, array2.T)  
print("Matrix product of array2 and its transpose:\n", matrix_product)

# Determinant of the matrix
determinant = np.linalg.det(square_matrix)  
print("Determinant of square_matrix:", determinant)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(square_matrix)  
print("Eigenvalues of square_matrix:", eigenvalues)
print("Eigenvectors of square_matrix:\n", eigenvectors)

Matrix product of array2 and its transpose:
 [[14 32]
 [32 77]]
Determinant of square_matrix: -2.0000000000000004
Eigenvalues of square_matrix: [-0.37228132  5.37228132]
Eigenvectors of square_matrix:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# Broadcasting rules
# Broadcasting operation
array_b = np.array([1, 2, 3])
broadcast_result = array2 + array_b  
print("Broadcasting result:\n", broadcast_result)


Broadcasting result:
 [[2 4 6]
 [5 7 9]]


In [ ]:
# Advanced array manipulation
# Rotate the array 90 degrees
rotated_array = np.rot90(array2)  
print("Rotated array2 by 90 degrees:\n", rotated_array)
# Flip the array
flipped_array = np.flip(array2)  
print("Flipped array2:\n", flipped_array)

Rotated array2 by 90 degrees:
 [[3 6]
 [2 5]
 [1 4]]
Flipped array2:
 [[6 5 4]
 [3 2 1]]


In [ ]:
# Creating specific arrays
# Identity matrix
identity_matrix = np.eye(3)  
print("Identity matrix:\n", identity_matrix)
# Diagonal matrix
diagonal_array = np.diag(array1)  
print("Diagonal array from array1:\n", diagonal_array)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal array from array1:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
# Memory layout
array_flags = array2.flags  
print("Memory layout of array2:\n", array_flags)

Memory layout of array2:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [ ]:
# Copying arrays
copied_array = np.copy(array1) 
print("Copied array1:", copied_array)
# Deep copy vs Shallow copy
deep_copy = np.copy(array2)  # Deep copy
shallow_copy = array2.view()  # Shallow copy
print("Deep copy of array2:\n", deep_copy)
print("Shallow copy (view) of array2:\n", shallow_copy)

Copied array1: [1 2 3 4 5]
Deep copy of array2:
 [[1 2 3]
 [4 5 6]]
Shallow copy (view) of array2:
 [[1 2 3]
 [4 5 6]]
